### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by zer0Kerbal** [linuxgurugamer/Antenna-Helper#3]
CustomBarnKit (CBK) allows for more than three levels of tracking station. Strategia, Bureaucracy and Komplexity (and more) make use of this.

Would you enhance this wonderful mod to look for and use additional levels of Tracking Station?

**Comment by linuxgurugamer** [comment]
I'll look into it.  I wanted to look at Komplexity, but found some issues on the forum re. the download links, posted there about it

**Comment by linuxgurugamer** [comment]
I'd appreciate it if you can point me to the code in Komplexity where it interfaces with CBK 

Edit:  never mind, I see your stuff is just a bunch of patches.  I'll have to look at CBK to get more info

**Comment by linuxgurugamer** [comment]
Umm, I'm wondering what, if anything, needs to be changed.  It already uses the trackingStationLevel from the game, as well as other game variables such as the DSN range.
